# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# DBTITLE 1,Bronze Ingestion from External Data
# MAGIC %md
# MAGIC # Bronze Layer Ingestion - External Data Source
# MAGIC
# MAGIC This notebook reads JSON files generated by the external ingestion script and loads them into the Bronze Delta table.
# MAGIC
# MAGIC ## Data Flow:
# MAGIC 1. **External Script** (Windows/Local) → Generates JSON files
# MAGIC 2. **Data Location**: `/Workspace/Users/swapniltake1@outlook.com/CryptoStream-Real-Time-Market-Data-Engineering-Platform/external_ingestion/data/`
# MAGIC 3. **Processing**: Read JSON → Extract metadata & data → Write to Bronze
# MAGIC
# MAGIC ## File Format:
# MAGIC ```json
# MAGIC {
# MAGIC   "metadata": {
# MAGIC     "batch_id": "BATCH_...",
# MAGIC     "ingestion_timestamp": "...",
# MAGIC     "source_system": "CoinGecko"
# MAGIC   },
# MAGIC   "data": [ /* array of coin records */ ]
# MAGIC }
# MAGIC ```

# COMMAND ----------

# DBTITLE 1,Define data location and list files
import json
import os
from datetime import datetime
from pyspark.sql.functions import *
from pyspark.sql.types import *

# Define the external ingestion data folder path
data_folder = "/Workspace/Users/swapniltake1@outlook.com/CryptoStream-Real-Time-Market-Data-Engineering-Platform/external_ingestion/data/"

# Control table to track processed files
control_table = "main.crypto_bronze.processed_files_control"

print(f"Looking for data files in: {data_folder}")
print("=" * 60)

# List all JSON files in the folder
try:
    files = dbutils.fs.ls(data_folder)
    json_files = [f for f in files if f.name.endswith('.json')]
    
    if not json_files:
        print("❌ No JSON files found!")
        print("\nTo generate data:")
        print("1. Run the coingecko_ingestion.py script on your local machine")
        print("2. It will save JSON files to the data folder")
        print("3. Re-run this notebook")
        raise FileNotFoundError("No JSON files in data folder")
    
    print(f"✓ Found {len(json_files)} JSON file(s)\n")
    
    # Create control table if it doesn't exist
    spark.sql(f"""
        CREATE TABLE IF NOT EXISTS {control_table} (
            file_name STRING,
            file_path STRING,
            file_size BIGINT,
            file_modification_time TIMESTAMP,
            processing_timestamp TIMESTAMP,
            batch_id STRING,
            record_count INT,
            status STRING
        )
        USING DELTA
    """)
    
    # Get list of already processed files
    processed_files_df = spark.table(control_table).filter(col("status") == "SUCCESS")
    processed_filenames = set([row.file_name for row in processed_files_df.select("file_name").collect()])
    
    print(f"📊 Already processed: {len(processed_filenames)} file(s)")
    
    # Filter out already processed files
    new_files = [f for f in json_files if f.name not in processed_filenames]
    
    print(f"🆕 New files to process: {len(new_files)}")
    print("=" * 60)
    
    if not new_files:
        print("\n✓ No new files to process. All files have been ingested.")
        print("\nAlready processed files:")
        for fname in processed_filenames:
            print(f"  ✓ {fname}")
        dbutils.notebook.exit("No new files to process")
    
    # Display new files to be processed
    print("\nNew files to process:")
    for f in new_files:
        file_date = datetime.fromtimestamp(f.modificationTime/1000)
        print(f"  📄 {f.name}")
        print(f"     Size: {f.size:,} bytes")
        print(f"     Modified: {file_date}\n")
    
    # Sort by modification time and get the oldest unprocessed file
    # (Process files in chronological order)
    sorted_files = sorted(new_files, key=lambda f: f.modificationTime)
    file_to_process = sorted_files[0]
    
    print("=" * 60)
    print(f"📌 Processing file: {file_to_process.name}")
    print(f"   (Processing oldest new file first)")
    print("=" * 60)
    
except Exception as e:
    print(f"❌ Error listing files: {e}")
    raise

# COMMAND ----------

# DBTITLE 1,Read and parse JSON file
# Read the JSON file content
file_path = file_to_process.path
file_name = file_to_process.name
file_size = file_to_process.size
file_mod_time = datetime.fromtimestamp(file_to_process.modificationTime/1000)

print(f"Reading file: {file_path}\n")

# Read the entire JSON file
file_content = spark.read.text(file_path, wholetext=True).collect()[0][0]
json_payload = json.loads(file_content)

# Extract metadata
metadata = json_payload['metadata']
print("📋 File Metadata:")
print("=" * 60)
print(f"Project Name       : {metadata['project_name']}")
print(f"Source System      : {metadata['source_system']}")
print(f"Batch ID           : {metadata['batch_id']}")
print(f"Ingestion Time     : {metadata['ingestion_timestamp']}")
print(f"Target Currency    : {metadata['target_currency']}")
print(f"Record Count       : {metadata['record_count']}")
print("=" * 60)

# Extract the data array
data_records = json_payload['data']
print(f"\n✓ Extracted {len(data_records)} cryptocurrency records")

# COMMAND ----------

# DBTITLE 1,Create DataFrame from data
# Create Spark DataFrame by writing temp JSON and reading back
# (Serverless compute workaround - no SparkContext, no local filesystem)

# Create a temporary workspace path for JSON lines
temp_json_dir = f"/Workspace/Users/swapniltake1@outlook.com/CryptoStream-Real-Time-Market-Data-Engineering-Platform/.temp/json_{metadata['batch_id']}"

# Write JSON records as newline-delimited JSON
json_content = '\n'.join([json.dumps(record) for record in data_records])
dbutils.fs.put(temp_json_dir + "/data.json", json_content, overwrite=True)

# Read using Spark's JSON reader (handles schema inference properly)
df_temp = spark.read.json(temp_json_dir)

# Collect all data into memory before cleaning up temp files
collected_data = df_temp.collect()
col_count = len(df_temp.columns)

# Clean up temporary file
dbutils.fs.rm(temp_json_dir, recurse=True)

# Recreate DataFrame from collected data
df_raw = spark.createDataFrame(collected_data, schema=df_temp.schema)
row_count = len(collected_data)

print(f"\n✓ Created DataFrame with {row_count} rows and {col_count} columns")
print("\nSchema:")
df_raw.printSchema()

print("\n📊 Sample Records:")
display(df_raw.limit(5))

# COMMAND ----------

# DBTITLE 1,Add Bronze layer metadata
# Add bronze layer metadata columns
df_bronze = (
    df_raw
    .withColumn("batch_id", lit(metadata['batch_id']))
    .withColumn("external_ingestion_timestamp", lit(metadata['ingestion_timestamp']).cast("timestamp"))
    .withColumn("bronze_ingestion_timestamp", current_timestamp())
    .withColumn("ingestion_date", current_timestamp().cast("date"))
    .withColumn("source_system", lit(metadata['source_system']))
    .withColumn("source_endpoint", lit(metadata['source_endpoint']))
    .withColumn("target_currency", lit(metadata['target_currency']))
    .withColumn("source_file", lit(latest_file.name))
    .withColumn("processing_timestamp", current_timestamp())
)

print("✓ Added bronze layer metadata columns")
print(f"\nTotal columns: {len(df_bronze.columns)}")
print(f"\nBronze DataFrame columns:")
for col in df_bronze.columns:
    print(f"  • {col}")

# Show sample with metadata
print("\n📊 Sample with Metadata:")
display(df_bronze.select(
    "id", "name", "symbol", "current_price", "market_cap",
    "batch_id", "bronze_ingestion_timestamp", "source_file"
).limit(5))

# COMMAND ----------

# DBTITLE 1,Write to Bronze Delta table
# Create schema if it doesn't exist
spark.sql("CREATE SCHEMA IF NOT EXISTS main.crypto_bronze")

# Define bronze table
bronze_table = "main.crypto_bronze.coingecko_market_data"

print(f"Writing to Delta table: {bronze_table}")
print("=" * 60)

# Write to Delta table with append mode
df_bronze.write \
    .format("delta") \
    .mode("append") \
    .option("mergeSchema", "true") \
    .saveAsTable(bronze_table)

record_count = df_bronze.count()
print(f"\n✓ Successfully wrote {record_count} records to {bronze_table}")
print(f"\nBatch ID: {metadata['batch_id']}")
print(f"External Ingestion: {metadata['ingestion_timestamp']}")
print(f"Bronze Processing: {datetime.now().isoformat()}")
print("=" * 60)

# COMMAND ----------

# DBTITLE 1,Record processed file in control table
# Record the file as successfully processed in control table
from pyspark.sql.types import StructType, StructField, StringType, LongType, TimestampType, IntegerType

control_record = [{
    "file_name": file_name,
    "file_path": file_path,
    "file_size": file_size,
    "file_modification_time": file_mod_time,
    "processing_timestamp": datetime.now(),
    "batch_id": metadata['batch_id'],
    "record_count": len(data_records),
    "status": "SUCCESS"
}]

control_schema = StructType([
    StructField("file_name", StringType(), True),
    StructField("file_path", StringType(), True),
    StructField("file_size", LongType(), True),
    StructField("file_modification_time", TimestampType(), True),
    StructField("processing_timestamp", TimestampType(), True),
    StructField("batch_id", StringType(), True),
    StructField("record_count", IntegerType(), True),
    StructField("status", StringType(), True)
])

control_df = spark.createDataFrame(control_record, schema=control_schema)

control_df.write \
    .format("delta") \
    .mode("append") \
    .saveAsTable(control_table)

print("\n" + "=" * 60)
print("✓ File recorded in control table")
print(f"  Table: {control_table}")
print(f"  File: {file_name}")
print(f"  Status: SUCCESS")
print("=" * 60)

# COMMAND ----------

# DBTITLE 1,Verify Bronze table
# Verify the data in bronze table
from pyspark.sql.functions import col, count, max as max_agg, min as min_agg, first

print("\n🔍 Verifying Bronze Table")
print("=" * 60)

bronze_table = "main.crypto_bronze.coingecko_market_data"
df_verify = spark.table(bronze_table)

total_records = df_verify.count()
latest_batch = df_verify.agg(max_agg("bronze_ingestion_timestamp")).collect()[0][0]

print(f"\nTotal records in Bronze: {total_records:,}")
print(f"Latest batch processed: {latest_batch}")

# Get batch statistics
print("\n📊 Batch Summary:")
df_verify.groupBy("batch_id") \
    .agg(
        count("*").alias("record_count"),
        min_agg("bronze_ingestion_timestamp").alias("processed_at"),
        first("source_file").alias("source_file")
    ) \
    .orderBy(col("processed_at").desc()) \
    .show(10, truncate=False)

print("\n📊 Latest Records:")
df_verify.select(
    "id", "name", "symbol", 
    "current_price", "market_cap", "market_cap_rank",
    "batch_id", "bronze_ingestion_timestamp"
) \
.orderBy(col("bronze_ingestion_timestamp").desc()) \
.show(10, truncate=False)

# COMMAND ----------

# DBTITLE 1,Summary and Next Steps
# MAGIC %md
# MAGIC ## ✅ Bronze Ingestion Complete!
# MAGIC
# MAGIC ### What was processed:
# MAGIC - Read JSON file from external_ingestion/data/
# MAGIC - Extracted metadata (batch_id, timestamps, source info)
# MAGIC - Extracted cryptocurrency data records
# MAGIC - Added Bronze layer metadata
# MAGIC - Wrote to Delta table: `main.crypto_bronze.coingecko_market_data`
# MAGIC
# MAGIC ---
# MAGIC
# MAGIC ### Next Steps:
# MAGIC
# MAGIC 1. **Silver Transformation**: Run the `silver_transformation` notebook to:
# MAGIC    - Clean and validate data
# MAGIC    - Remove duplicates
# MAGIC    - Standardize schema
# MAGIC    - Write to `main.crypto_silver.crypto_market`
# MAGIC
# MAGIC 2. **Gold Analytics**: Run the `gold_market_analytics` notebook to:
# MAGIC    - Create market snapshots
# MAGIC    - Calculate top gainers/losers
# MAGIC    - Generate market metrics
# MAGIC
# MAGIC 3. **Generate Fresh Data**: 
# MAGIC    - Run `coingecko_ingestion.py` on your local machine to fetch new data
# MAGIC    - Re-run this notebook to process the new file
# MAGIC
# MAGIC ---
# MAGIC
# MAGIC ### Data Flow:
# MAGIC ```
# MAGIC External Script (Windows/Local)
# MAGIC          ↓
# MAGIC JSON File (external_ingestion/data/)
# MAGIC          ↓
# MAGIC Bronze Layer (this notebook)
# MAGIC          ↓
# MAGIC Silver Layer (cleaning)
# MAGIC          ↓
# MAGIC Gold Layer (analytics)
# MAGIC ```